import {
  Apple,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Cat,
  Code,
  Coffee,
  Dog,
  Droplet,
  Dumbbell,
  Flame,
  Footprints,
  GraduationCap,
  Guitar,
  Heart,
  Languages,
  Leaf,
  Moon,
  Mountain,
  Music,
  Palette,
  PenTool,
  Phone,
  PiggyBank,
  Pill,
  Salad,
  ShowerHead,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Timer,
  Trophy,
  Users,
  Utensils,
  Wallet,
  Waves,
  type LucideIcon,
} from 'lucide-react';

export const LUCIDE_PRAEFIX = 'lucide:';
export const STANDARD_ICON = '💧';

/** Kuratierte Icon-Auswahl - bewusst klein, damit das Bundle schlank bleibt. */
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  droplet: Droplet,
  coffee: Coffee,
  apple: Apple,
  salad: Salad,
  utensils: Utensils,
  pill: Pill,
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  waves: Waves,
  mountain: Mountain,
  timer: Timer,
  heart: Heart,
  brain: Brain,
  smile: Smile,
  moon: Moon,
  sun: Sun,
  bed: Bed,
  'shower-head': ShowerHead,
  leaf: Leaf,
  'book-open': BookOpen,
  'pen-tool': PenTool,
  languages: Languages,
  'graduation-cap': GraduationCap,
  code: Code,
  briefcase: Briefcase,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  music: Music,
  guitar: Guitar,
  palette: Palette,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trophy: Trophy,
  flame: Flame,
  users: Users,
  phone: Phone,
  dog: Dog,
  cat: Cat,
};

export const EMOJIS: readonly string[] = [
  '💧',
  '🥤',
  '☕',
  '🍎',
  '🥗',
  '🥦',
  '🍳',
  '🥛',
  '🏃',
  '🚴',
  '🧘',
  '🤸',
  '⚽',
  '🏊',
  '🥾',
  '💪',
  '📚',
  '📖',
  '🎓',
  '🧠',
  '💡',
  '💻',
  '🎯',
  '🗒️',
  '🎸',
  '🎹',
  '🎨',
  '🎬',
  '🌱',
  '🌞',
  '🌙',
  '😴',
  '🚿',
  '🦷',
  '💊',
  '🧹',
  '💰',
  '🐕',
  '🐈',
  '📞',
  '💬',
  '❤️',
  '🙏',
  '🎉',
  '⭐',
  '🔥',
];

export function istLucideIcon(icon: string): boolean {
  return icon.startsWith(LUCIDE_PRAEFIX);
}

export function lucideKomponente(icon: string): LucideIcon | undefined {
  if (!istLucideIcon(icon)) return undefined;
  return LUCIDE_ICONS[icon.slice(LUCIDE_PRAEFIX.length)];
}

export const LUCIDE_SCHLUESSEL = Object.keys(LUCIDE_ICONS).map((k) => `${LUCIDE_PRAEFIX}${k}`);
